line-length = 88
indent-width = 4

[lint]
fixable = ["ALL"]
ignore = ["F403"]
select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I']
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
from-first = true


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
